
import Head from "next/head";
import Container from "react-bootstrap/Container";
import UniorHeader from "@/components/UniorHeader";
import UniorMain from '@/components/UniorMain';
import UniorSidebar from '@/components/UniorSidebar';
import UniorSearchModal from '@/components/UniorSearchModal';
import UniorSettingsModal from '@/components/UniorSettingsModal';
import UniorFooter from "@/components/UniorFooter";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bootstrap w/ React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main" className="wrapper bg-noise">
        <UniorHeader />
        <UniorMain />
        <UniorSidebar />
        <UniorSearchModal />
        <UniorSettingsModal />
        <UniorFooter />
      </Container>
    </>
  );
}